es:
  host: localhost
  port: 9200
  name: tyredb2
db:
  type: sqlite3
  name: data/mdm.db
  tablename_s_data: "s_data"
  tablename_w_data_mapping_fields: "w_data_mapping_fields"
  tablename_w_data_mapping_values: "w_data_mapping_values"
  tablename_dim_data: "data"
  tablename_fields: "fields"
  tablename_fields_values: "fields_values"
fs:
  data: data
  format: json
  source_dir: ../scrapy_tyres/data/sources
  target_dir: www/data
mdm:
  uid: ean
  constaints:
    required:
      - brand
      - manufacturer_number
      - product
      - width
      - height
      - rim
      - season
    sufficient:
      - [brand, manufacturer_number]
